import X from 'lucide-react-native/icons/x';
import React, { useEffect, useState } from 'react';
import { Modal, Pressable, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAppTheme } from '../../theme';
import { AppText } from '../AppText';

export type LabFilterValues = { sort: 'none' | 'az' | 'za'; price: 'all' | 'under400' | '400to500' | 'above500' };
type Props = { visible: boolean; value: LabFilterValues; onClose: () => void; onApply: (value: LabFilterValues) => void };
const initial: LabFilterValues = { sort: 'none', price: 'all' };

export function LabFilterSheet({ visible, value, onClose, onApply }: Props) {
  const { theme } = useAppTheme();
  const [draft, setDraft] = useState(value);
  useEffect(() => { if (visible) setDraft(value); }, [value, visible]);
  const choice = (label: string, active: boolean, onPress: () => void) => <Pressable onPress={onPress} style={[styles.choice, { borderColor: active ? theme.colors.primary : theme.colors.border, backgroundColor: active ? theme.colors.primarySoft : theme.colors.surface }]}><View style={[styles.radio, { borderColor: active ? theme.colors.primary : theme.colors.border }]}>{active && <View style={[styles.dot, { backgroundColor: theme.colors.primary }]} />}</View><AppText color={active ? theme.colors.primary : theme.colors.text} style={styles.choiceText} weight={active ? '700' : '500'}>{label}</AppText></Pressable>;
  return <Modal animationType="slide" transparent statusBarTranslucent visible={visible} onRequestClose={onClose}><View style={styles.modal}><Pressable style={styles.backdrop} onPress={onClose} /><SafeAreaView edges={['bottom']} style={[styles.sheet, { backgroundColor: theme.colors.surface }]}><View style={styles.header}><AppText style={styles.title} weight="800">Filter labs</AppText><Pressable onPress={onClose} style={[styles.close, { backgroundColor: theme.colors.surfaceMuted }]}><X color={theme.colors.text} size={20} /></Pressable></View><AppText style={styles.label} weight="700">Sort by name</AppText><View style={styles.options}>{choice('A to Z', draft.sort === 'az', () => setDraft({ ...draft, sort: draft.sort === 'az' ? 'none' : 'az' }))}{choice('Z to A', draft.sort === 'za', () => setDraft({ ...draft, sort: draft.sort === 'za' ? 'none' : 'za' }))}</View><AppText style={styles.label} weight="700">Price range</AppText><View style={styles.options}>{choice('Under ₹400', draft.price === 'under400', () => setDraft({ ...draft, price: 'under400' }))}{choice('₹400 – ₹500', draft.price === '400to500', () => setDraft({ ...draft, price: '400to500' }))}{choice('Above ₹500', draft.price === 'above500', () => setDraft({ ...draft, price: 'above500' }))}</View><View style={styles.actions}><Pressable onPress={() => setDraft(initial)} style={[styles.clear, { borderColor: theme.colors.border }]}><AppText style={styles.actionText} weight="700">Clear all</AppText></Pressable><Pressable onPress={() => onApply(draft)} style={[styles.apply, { backgroundColor: theme.colors.primary }]}><AppText color="#FFFFFF" style={styles.actionText} weight="700">Apply filters</AppText></Pressable></View></SafeAreaView></View></Modal>;
}
const styles = StyleSheet.create({ modal: { flex: 1, justifyContent: 'flex-end' }, backdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(2,6,23,.5)' }, sheet: { borderTopLeftRadius: 25, borderTopRightRadius: 25, padding: 18 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }, title: { fontSize: 21, lineHeight: 26 }, close: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, label: { fontSize: 13, lineHeight: 17, marginBottom: 9 }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 }, choice: { height: 38, borderWidth: 1, borderRadius: 11, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 11 }, radio: { width: 15, height: 15, borderRadius: 8, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, dot: { width: 7, height: 7, borderRadius: 4 }, choiceText: { fontSize: 10, lineHeight: 13 }, actions: { flexDirection: 'row', gap: 10, marginTop: 2 }, clear: { flex: 1, height: 46, borderWidth: 1, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, apply: { flex: 1.5, height: 46, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, actionText: { fontSize: 12, lineHeight: 16 } });
